# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

import sys #
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QIcon #
from PyQt5.QtCore import pyqtSlot #
from show_seat import *
from select_seat import*
from charging_time import *
from order_product import * #
        
libpaths = QtWidgets.QApplication.libraryPaths() #추가
libpaths.append("C:\\Users\사용자\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\PyQt5\Qt\plugins")
QtWidgets.QApplication.setLibraryPaths(libpaths)
'''
from openpyxl import load_workbook
wb = load_workbook("좌석관리.xlsx")
ws = wb.active
wb1 = load_workbook("결제로그.xlsx")
ws1 = wb1.active
'''
class Ui_MainWindow(object):
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 856)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 70, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 300, 80, 30)) 
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")  
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(450, 60, 71, 31))
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(950, 730, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(450, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(750, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(850, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(950, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(550, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(650, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(750, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(850, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(950, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(450, 320, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(550, 320, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(650, 320, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(750, 320, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(850, 320, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(950, 320, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(450, 450, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(550, 450, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(650, 450, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(750, 450, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(850, 450, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(950, 450, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(450, 590, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(550, 590, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(650, 590, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(750, 590, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(850, 590, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(950, 590, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(600, 625, 400, 250))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(80, 120, 600, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(90, 630, 261, 81))
        self.textEdit.setObjectName("textEdit")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(450, 90, 71, 71))
        self.label1.setStyleSheet("background:rgb(255, 255, 255)")
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(550, 90, 71, 71))
        self.label2.setStyleSheet("background:rgb(255, 255, 255)")
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(650, 90, 71, 71))
        self.label3.setStyleSheet("background:rgb(255, 255, 255)")
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(750, 90, 71, 71))
        self.label4.setStyleSheet("background:rgb(255, 255, 255)")
        self.label4.setText("")
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(850, 90, 71, 71))
        self.label5.setStyleSheet("background:rgb(255, 255, 255)")
        self.label5.setText("")
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setGeometry(QtCore.QRect(950, 90, 71, 71))
        self.label6.setStyleSheet("background:rgb(255, 255, 255)")
        self.label6.setText("")
        self.label6.setObjectName("label6")
        self.label9 = QtWidgets.QLabel(self.centralwidget)
        self.label9.setGeometry(QtCore.QRect(650, 220, 71, 71))
        self.label9.setStyleSheet("background:rgb(255, 255, 255)")
        self.label9.setText("")
        self.label9.setObjectName("label9")
        self.label12 = QtWidgets.QLabel(self.centralwidget)
        self.label12.setGeometry(QtCore.QRect(950, 220, 71, 71))
        self.label12.setStyleSheet("background:rgb(255, 255, 255)")
        self.label12.setText("")
        self.label12.setObjectName("label12")
        self.label8 = QtWidgets.QLabel(self.centralwidget)
        self.label8.setGeometry(QtCore.QRect(550, 220, 71, 71))
        self.label8.setStyleSheet("background:rgb(255, 255, 255)")
        self.label8.setText("")
        self.label8.setObjectName("label8")
        self.label11 = QtWidgets.QLabel(self.centralwidget)
        self.label11.setGeometry(QtCore.QRect(850, 220, 71, 71))
        self.label11.setStyleSheet("background:rgb(255, 255, 255)")
        self.label11.setText("")
        self.label11.setObjectName("label11")
        self.label10 = QtWidgets.QLabel(self.centralwidget)
        self.label10.setGeometry(QtCore.QRect(750, 220, 71, 71))
        self.label10.setStyleSheet("background:rgb(255, 255, 255)")
        self.label10.setText("")
        self.label10.setObjectName("label10")
        self.label7 = QtWidgets.QLabel(self.centralwidget)
        self.label7.setGeometry(QtCore.QRect(450, 220, 71, 71))
        self.label7.setStyleSheet("background:rgb(255, 255, 255)")
        self.label7.setText("")
        self.label7.setObjectName("label7")
        self.label15 = QtWidgets.QLabel(self.centralwidget)
        self.label15.setGeometry(QtCore.QRect(650, 350, 71, 71))
        self.label15.setStyleSheet("background:rgb(255, 255, 255)")
        self.label15.setText("")
        self.label15.setObjectName("label15")
        self.label18 = QtWidgets.QLabel(self.centralwidget)
        self.label18.setGeometry(QtCore.QRect(950, 350, 71, 71))
        self.label18.setStyleSheet("background:rgb(255, 255, 255)")
        self.label18.setText("")
        self.label18.setObjectName("label18")
        self.label14 = QtWidgets.QLabel(self.centralwidget)
        self.label14.setGeometry(QtCore.QRect(550, 350, 71, 71))
        self.label14.setStyleSheet("background:rgb(255, 255, 255)")
        self.label14.setText("")
        self.label14.setObjectName("label14")
        self.label17 = QtWidgets.QLabel(self.centralwidget)
        self.label17.setGeometry(QtCore.QRect(850, 350, 71, 71))
        self.label17.setStyleSheet("background:rgb(255, 255, 255)")
        self.label17.setText("")
        self.label17.setObjectName("label17")
        self.label16 = QtWidgets.QLabel(self.centralwidget)
        self.label16.setGeometry(QtCore.QRect(750, 350, 71, 71))
        self.label16.setStyleSheet("background:rgb(255, 255, 255)")
        self.label16.setText("")
        self.label16.setObjectName("label16")
        self.label13 = QtWidgets.QLabel(self.centralwidget)
        self.label13.setGeometry(QtCore.QRect(450, 350, 71, 71))
        self.label13.setStyleSheet("background:rgb(255, 255, 255)")
        self.label13.setText("")
        self.label13.setObjectName("label13")
        self.label21 = QtWidgets.QLabel(self.centralwidget)
        self.label21.setGeometry(QtCore.QRect(650, 480, 71, 71))
        self.label21.setStyleSheet("background:rgb(255, 255, 255)")
        self.label21.setText("")
        self.label21.setObjectName("label21")
        self.label24 = QtWidgets.QLabel(self.centralwidget)
        self.label24.setGeometry(QtCore.QRect(950, 480, 71, 71))
        self.label24.setStyleSheet("background:rgb(255, 255, 255)")
        self.label24.setText("")
        self.label24.setObjectName("label24")
        self.label20 = QtWidgets.QLabel(self.centralwidget)
        self.label20.setGeometry(QtCore.QRect(550, 480, 71, 71))
        self.label20.setStyleSheet("background:rgb(255, 255, 255)")
        self.label20.setText("")
        self.label20.setObjectName("label20")
        self.label23 = QtWidgets.QLabel(self.centralwidget)
        self.label23.setGeometry(QtCore.QRect(850, 480, 71, 71))
        self.label23.setStyleSheet("background:rgb(255, 255, 255)")
        self.label23.setText("")
        self.label23.setObjectName("label23")
        self.label22 = QtWidgets.QLabel(self.centralwidget)
        self.label22.setGeometry(QtCore.QRect(750, 480, 71, 71))
        self.label22.setStyleSheet("background:rgb(255, 255, 255)")
        self.label22.setText("")
        self.label22.setObjectName("label22")
        self.label19 = QtWidgets.QLabel(self.centralwidget)
        self.label19.setGeometry(QtCore.QRect(450, 480, 71, 71))
        self.label19.setStyleSheet("background:rgb(255, 255, 255)")
        self.label19.setText("")
        self.label19.setObjectName("label19")
        self.label27 = QtWidgets.QLabel(self.centralwidget)
        self.label27.setGeometry(QtCore.QRect(650, 620, 71, 71))
        self.label27.setStyleSheet("background:rgb(255, 255, 255)")
        self.label27.setText("")
        self.label27.setObjectName("label27")
        self.label30 = QtWidgets.QLabel(self.centralwidget)
        self.label30.setGeometry(QtCore.QRect(950, 620, 71, 71))
        self.label30.setStyleSheet("background:rgb(255, 255, 255)")
        self.label30.setText("")
        self.label30.setObjectName("label30")
        self.label26 = QtWidgets.QLabel(self.centralwidget)
        self.label26.setGeometry(QtCore.QRect(550, 620, 71, 71))
        self.label26.setStyleSheet("background:rgb(255, 255, 255)")
        self.label26.setText("")
        self.label26.setObjectName("label26")
        self.label29 = QtWidgets.QLabel(self.centralwidget)
        self.label29.setGeometry(QtCore.QRect(850, 620, 71, 71))
        self.label29.setStyleSheet("background:rgb(255, 255, 255)")
        self.label29.setText("")
        self.label29.setObjectName("label29")
        self.label28 = QtWidgets.QLabel(self.centralwidget)
        self.label28.setGeometry(QtCore.QRect(750, 620, 71, 71))
        self.label28.setStyleSheet("background:rgb(255, 255, 255)")
        self.label28.setText("")
        self.label28.setObjectName("label28")
        self.label25 = QtWidgets.QLabel(self.centralwidget)
        self.label25.setGeometry(QtCore.QRect(450, 620, 71, 71))
        self.label25.setStyleSheet("background:rgb(255, 255, 255)")
        self.label25.setText("")
        self.label25.setObjectName("label25")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 200, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 240, 241, 51))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        

#_____________________________________________________________________________________________
        # 화면에 현재 좌석 상황 보여주기
        from openpyxl import load_workbook
        wb = load_workbook("좌석관리.xlsx")
        ws = wb.active
        
        list = [self.label1, self.label2, self.label3, self.label4,self.label5,self.label6,
                self.label7, self.label8, self.label9, self.label10,self.label11,self.label12,
                self.label13, self.label14, self.label15, self.label16,self.label17,self.label18,
                self.label19, self.label20, self.label21, self.label22,self.label23,self.label24,
                self.label25, self.label26, self.label27, self.label28,self.label29,self.label30,]

        for rowNum in range(2, ws.max_row+1):
            if (ws.cell(row=rowNum,column=3).value == True) :
                list[rowNum-2].setStyleSheet("background-color:rgb(255, 255, 127);")
            if (ws.cell(row=rowNum,column=2).value == '커플석') :
                list[rowNum-2].setText("♥♥♥♥")
            if (ws.cell(row=rowNum,column=2).value == '고사양게임석') :
                list[rowNum-2].setText("┌▤〓")
            if (ws.cell(row=rowNum,column=2).value == '티켓팅석') :
                list[rowNum-2].setText("(^_^)b")


#-----------------------------------------------------------------------------------------------------------------
# 이벤트 핸들러
        self.pushButton.clicked.connect(self.showClicked)   # 좌석 추천
        self.pushButton_2.clicked.connect(self.selectClicked)   # 좌석 선택
        self.pushButton_3.clicked.connect(self.nextClicked)  # 시간 충전
#-----------------------------------------------------------------------------------------------------------------
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        
#----------------------------------------------------------------------------------------------
#다른 윈도우와 연결


    # 좌석 추천   
    def showClicked(self):
        from openpyxl import load_workbook
        wb = load_workbook("좌석관리.xlsx")
        ws = wb.active
        wb1 = load_workbook("결제로그.xlsx")
        ws1 = wb1.active

        list = [self.label1, self.label2, self.label3, self.label4,self.label5,self.label6,
                self.label7, self.label8, self.label9, self.label10,self.label11,self.label12,
                self.label13, self.label14, self.label15, self.label16,self.label17,self.label18,
                self.label19, self.label20, self.label21, self.label22,self.label23,self.label24,
                self.label25, self.label26, self.label27, self.label28,self.label29,self.label30,]

        seats = read_seatdata_fromxlsx()
        #print(seats)
        new_seats = check_six(seats)
        #print(new_seats)

        # 추천 좌석을 파란색으로 표시
        for i in range(0, 5) :
            for j in range(0, 6):
                if (new_seats[i][j] == '*') :
                    index = i*6 + j
                    list[index].setStyleSheet("background-color:rgb(170, 170, 255);")


    # 좌석 선택
    def selectClicked(self):
        from openpyxl import load_workbook
        wb = load_workbook("좌석관리.xlsx")
        ws = wb.active
        wb1 = load_workbook("결제로그.xlsx")
        ws1 = wb1.active

        selected_seat = self.lineEdit.text()
        selected_seat = int(selected_seat)

        if(ws.cell(row= selected_seat + 1, column = 3).value == True):
            msgBox = QMessageBox.about(None, '좌석선택', '이미 사용중인 좌석입니다. 다시 선택해주십시오.')
            return

        else :
            content = str(selected_seat)+'번 좌석이 선택되었습니다.'
            msgBox = QMessageBox.about(None, '좌석선택', content)
            ws1.cell(row=ws1.max_row, column = 7).value = selected_seat
            wb1.save('결제로그.xlsx')
            return

    # 시간 충전
    def nextClicked(self) :
        msgBox = QMessageBox.about(None, '안내문', '시간충전으로 넘어갑니다.')
        ####################여기에 시간 충전 연결
        '''
        self.window = QtWidgets.QDialog()
        self.ui = Ui_OrderProduct()
        self.ui.setupUi(self.window)
        self.window.show()
        '''
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ChargeTime()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "좌석선택"))
        self.pushButton.setText(_translate("MainWindow", "좌석추천"))
        self.pushButton_2.setText(_translate("MainWindow", "좌석선택"))
        self.pushButton_3.setText(_translate("MainWindow", "다음 >>"))
        self.label_1.setText(_translate("MainWindow", "      1"))
        self.label_2.setText(_translate("MainWindow", "      2"))
        self.label_3.setText(_translate("MainWindow", "      3"))
        self.label_4.setText(_translate("MainWindow", "      4"))
        self.label_5.setText(_translate("MainWindow", "      5"))
        self.label_6.setText(_translate("MainWindow", "      6"))
        self.label_7.setText(_translate("MainWindow", "      7"))
        self.label_8.setText(_translate("MainWindow", "      8"))
        self.label_9.setText(_translate("MainWindow", "      9"))
        self.label_10.setText(_translate("MainWindow", "     10"))
        self.label_11.setText(_translate("MainWindow", "     11"))
        self.label_12.setText(_translate("MainWindow", "     12"))
        self.label_13.setText(_translate("MainWindow", "     13"))
        self.label_14.setText(_translate("MainWindow", "     14"))
        self.label_15.setText(_translate("MainWindow", "     15"))
        self.label_16.setText(_translate("MainWindow", "     16"))
        self.label_17.setText(_translate("MainWindow", "     17"))
        self.label_18.setText(_translate("MainWindow", "    18"))
        self.label_19.setText(_translate("MainWindow", "     19"))
        self.label_20.setText(_translate("MainWindow", "     20"))
        self.label_21.setText(_translate("MainWindow", "     21"))
        self.label_22.setText(_translate("MainWindow", "     22"))
        self.label_23.setText(_translate("MainWindow", "     23"))
        self.label_24.setText(_translate("MainWindow", "     24"))
        self.label_25.setText(_translate("MainWindow", "     25"))
        self.label_26.setText(_translate("MainWindow", "     26"))
        self.label_27.setText(_translate("MainWindow", "     27"))
        self.label_28.setText(_translate("MainWindow", "     28"))
        self.label_29.setText(_translate("MainWindow", "     29"))
        self.label_30.setText(_translate("MainWindow", "     30"))
        self.label_31.setText(_translate("MainWindow", "     노란색 좌석은 현재 사용중인 좌석입니다"))
        self.label_32.setText(_translate("MainWindow", "     *(2명 이상)좌석 추천을 원하실 경우\n     추천 좌석 버튼을 클릭해주십시오.\n     *파란색 좌석은 추천 좌석입니다"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">고사양 게임석 : ┌▤〓</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">커플석 : ♥♥♥♥</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">수강신청 / 티켓팅석 : (^_^)b</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "   선택할 좌석 번호"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

